name: Build & Publish TwitterCloneFrontend

on:
  push:
    branches: [master]
  # run it during pull request
  pull_request:
    branches: []

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          file: ./Dockerfile
          # Note: tags has to be all lower-case
          tags: |
            stijnboss12/twitterclone.frontend:latest 
            ghcr.io/stijnboss12/twitterclone.frontend:latest
          # build on feature branches, push only on main branch
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
